---
# tasks file for monitor_cluster

# Monitor cluster installation
- name: Wait for 60 min until the cluster is installed
  uri:
    url: "{{ URL_ASSISTED_INSTALLER_CLUSTER }}"
    method: GET
    headers:
      Authorization: "Bearer {{ access_token }}"
      Content-Type: "json"
    status_code: [200, 201]
    return_content: True
  register: cluster
  until: cluster.json.status in ['installed', 'error', 'cancelled']
  retries: 60
  delay: 60
  delegate_to: bastion

- name: "Fail installation because user cancelled (ERROR)"
  fail:
    msg: "Cluster installation failed - Reset the installation process to return to the configuration and try again"
  when: cluster.json.status == 'error'
  delegate_to: bastion

- name: "Fail installation because user cancelled (CANCELLED)"
  fail:
    msg: "Installation was canceled by user - Reset the installation process to return to the configuration and try again"
  when: cluster.json.status == 'cancelled'
  delegate_to: bastion
